### ISSUE TITLE
Linker Error LNK2019 in VS2015

### ISSUE THREAD

**Issue by samfar22** [Intel-Media-SDK/samples#4]
When compiling the code with VS2015, I get the following linker error:

`Error  LNK2019 unresolved external symbol _swscanf_s referenced in function "private: bool __thiscall MFX::MFXPluginsInFS::ParseKVPair(wchar_t *,wchar_t *,class MFX::PluginDescriptionRecord &)" (?ParseKVPair@MFXPluginsInFS@MFX@@AAE_NPA_W0AAVPluginDescriptionRecord@2@@Z) tutorial_screen_capture C:\simple_10_screen_capture\libmfx.lib(mfx_plugin_hive.obj)`

I have installed Intel Media SDK 2016 R2. I am getting the same error on two different PCs. Please help. Thanks.

**Comment by cameronelliott** [comment]
@samfar22 

This occurs because the samples includes libmfx.lib compiled on a pre VS2015 version of Visual Studio.

You can fix this in one of two ways:
1. Add "legacy_stdio_definitions.lib" to the inputs section of which ever sample you are compiling.
   More info: https://msdn.microsoft.com/en-us/library/bb531344.aspx
   -or-
2. Add the libmfx.vcxproj to the solution of the sample you are compiling, and then in VS, 'Add Reference' on the project you are trying to compile to link it to libmfx, then finally, remove libmfx.lib from the sample's linker input field.

**Comment by amaslenn** [comment]
@cameron-elliott **Thank you!** 
@samfar22 have you fixed it?
